import random

import requests
from random_user_agent.user_agent import UserAgent
from random_user_agent.params import SoftwareName, OperatingSystem
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from function.randomName import get_random_name

scope = ["https://spreadsheets.google.com/feeds", 'https://www.googleapis.com/auth/spreadsheets',
         "https://www.googleapis.com/auth/drive.file", "https://www.googleapis.com/auth/drive"]

creds = ServiceAccountCredentials.from_json_keyfile_name("creds2.json", scope)
client = gspread.authorize(creds)
googleSheetName = client.open('Data')
sheet = googleSheetName.worksheet('data yahoo')

software_names = [SoftwareName.CHROME.value]
operating_systems = [OperatingSystem.WINDOWS.value, OperatingSystem.LINUX.value]

user_agent_rotator = UserAgent(software_names=software_names, operating_systems=operating_systems, limit=100)


def get_geolocation_by_ip(proxy_ip):
    access_token = '30bcb98e8c7e70'
    url = f"https://ipinfo.io/{proxy_ip}?token={access_token}"
    response = requests.get(url)
    data = response.json()
    location = data['loc'].split(',')
    return {'latitude': location[0], 'longitude': location[1]}


def get_public_ip_via_proxy(proxy):
    response = requests.get("https://httpbin.org/ip", proxies=proxy)
    ip = response.json()["origin"]
    return ip


def update_status(numberOfRow, status):
    sheet.update_cell(numberOfRow, 9, status)


def generate_random_profile(proxy_ip):
    resolutions = ['1920x1080', '1366x768', '1280x800', '1536x864', '1440x900', '1600x900', '1280x1024', '1024x768']
    resolution = random.choice(resolutions)

    device_memories = [4, 8, 16, 32]
    device_memory = random.choice(device_memories)

    hardware_concurrency = random.choice([2, 4, 8, 16])

    geolocation = get_geolocation_by_ip(proxy_ip)

    enable_vulnerable = random.choice([True, False])
    enable_flash = random.choice([True, False])

    return {
        'resolution': resolution,
        'device_memory': device_memory,
        'hardware_concurrency': hardware_concurrency,
        'geolocation': geolocation,
        'plugins': {'enable_vulnerable': enable_vulnerable, 'enable_flash': enable_flash}
    }


def create_profile(numberOfRow, GoLogin):
    first_name, last_name = get_random_name()

    sheet.update_cell(numberOfRow, 1, first_name)
    sheet.update_cell(numberOfRow, 2, last_name)

    GologinName = first_name

    gl = GoLogin({
        "token": "ey0",
    })
    proxies = [
        "hyperion.p.shifter.io:17010",
        "hyperion.p.shifter.io:17011",
        "hyperion.p.shifter.io:17012",
        "hyperion.p.shifter.io:17013",
        "hyperion.p.shifter.io:17014"
    ]

    proxy = random.choice(proxies).split(":")
    random_proxy_choice = random.choice(proxies)
    print('random proxy choice:', random_proxy_choice)

    proxy_url = f"http://{random_proxy_choice}"
    proxy_dict = {"http": proxy_url, "https": proxy_url}

    public_ip = get_public_ip_via_proxy(proxy_dict)
    print('Using ip: ', public_ip)
    user_agent = user_agent_rotator.get_random_user_agent()
    random_profile = generate_random_profile(public_ip)
    # profile_id = gl.create(
    #     {'name': GologinName, 'notes': '', 'facebookAccountData': {'notParsedData': {}}, 'browserType': 'chrome',
    #      'canBeRunning': True, 'os': 'win', 'startUrl': '', 'autoLang': True, 'bookmarks': {},
    #      'googleServicesEnabled': False, 'isBookmarksSynced': True, 'lockEnabled': False, 'debugMode': False,
    #      'navigator': {
    #          'userAgent': user_agent,
    #          'resolution': random_profile['resolution'], 'language': 'en-US,en;q=0.9', 'platform': 'Win32',
    #          'hardwareConcurrency': random_profile['hardware_concurrency'],
    #          'doNotTrack': None, 'deviceMemory': random_profile['device_memory'], 'maxTouchPoints': 0},
    #      'storage': {'local': True, 'extensions': True, 'bookmarks': True, 'history': True, 'passwords': True,
    #                  'session': True, 'indexedDb': False, 'enableExternalExtensions': False}, 'proxyEnabled': True,
    #      'autoProxyServer': '', 'autoProxyUsername': '', 'autoProxyPassword': '',
    #      'proxy': {'id': '660d2c05de39fbed96f3429d', 'mode': 'http', 'host': proxy[0], 'port': proxy[1],
    #                'autoProxyRegion': 'us', 'torProxyRegion': 'us', 'username': '', 'password': ''}, 'dns': '',
    #      'plugins': random_profile['plugins'],
    #      'timezone': {'enabled': True, 'fillBasedOnIp': True, 'timezone': ''},
    #      'geolocation': {'mode': 'prompt', 'enabled': True, 'customize': True, 'fillBasedOnIp': True,
    #                      'isCustomCoordinates': False, 'latitude': 0, 'longitude': 0, 'accuracy': 10},
    #      'audioContext': {'mode': 'noise', 'noise': 2.174740528118e-08}, 'canvas': {'mode': 'off', 'noise': 0.76474414},
    #      'fonts': {'enableMasking': True, 'enableDomRect': True,
    #                'families': ['AIGDT', 'AMGDT', 'Arial', 'Arial Baltic', 'Arial Black', 'Arial CE', 'Arial Cyr',
    #                             'Arial Greek', 'Arial Hebrew', 'Arial MT', 'Arial Narrow', 'Arial Rounded MT Bold',
    #                             'Arial TUR', 'Arial Unicode MS', 'Calibri', 'Calibri Light', 'Cambria', 'Cambria Math',
    #                             'Candara', 'Comic Sans MS', 'Consolas', 'Constantia', 'Corbel', 'Courier',
    #                             'Courier New', 'Courier New Baltic', 'Courier New CE', 'Courier New Cyr',
    #                             'Courier New Greek', 'Courier New TUR', 'David', 'David Libre', 'DejaVu Sans',
    #                             'DejaVu Sans Condensed', 'DejaVu Sans Mono', 'DejaVu Serif', 'DejaVu Serif Condensed',
    #                             'Ebrima', 'Frank Ruehl', 'Frank Ruehl Libre Black', 'Frank Ruehl Libre Light',
    #                             'Franklin Gothic Book', 'Franklin Gothic Demi', 'Franklin Gothic Demi Cond',
    #                             'Franklin Gothic Heavy', 'Franklin Gothic Medium', 'Franklin Gothic Medium Cond',
    #                             'Gabriola', 'Gadugi', 'Georgia', 'Gill Sans', 'Gill Sans MT', 'Gill Sans MT Condensed',
    #                             'Gill Sans MT Ext Condensed Bold', 'Gill Sans Ultra Bold',
    #                             'Gill Sans Ultra Bold Condensed', 'Impact', 'KacstBook', 'KacstLetter', 'KacstNaskh',
    #                             'KacstOffice', 'KacstTitlel', 'Leelawadee', 'Liberation Mono', 'Liberation Sans',
    #                             'Liberation Sans Narrow', 'Liberation Serif', 'Lucida Bright', 'Lucida Calligraphy',
    #                             'Lucida Console', 'Lucida Sans Unicode', 'MS Gothic', 'MS LineDraw', 'MS Mincho',
    #                             'MS Outlook', 'MS PGothic', 'MS PMincho', 'MS Reference Sans Serif',
    #                             'MS Reference Specialty', 'MS Sans Serif', 'MS Serif', 'MS UI Gothic', 'MV Boli',
    #                             'Malgun Gothic', 'Marlett', 'Microsoft Himalaya', 'Microsoft JhengHei',
    #                             'Microsoft JhengHei UI', 'Microsoft PhagsPa', 'Microsoft Sans Serif',
    #                             'Microsoft Tai Le', 'Microsoft Uighur', 'Microsoft YaHei', 'Microsoft Yi Baiti',
    #                             'MingLiU', 'MingLiU-ExtB', 'MingLiU_HKSCS', 'MingLiU_HKSCS-ExtB', 'Miriam',
    #                             'Miriam Fixed', 'Miriam Libre', 'Mongolian Baiti', 'NSimSun', 'Nirmala UI', 'Noto Mono',
    #                             'Noto Sans', 'Noto Sans Arabic UI', 'Noto Sans CJK HK', 'Noto Sans CJK JP',
    #                             'Noto Sans CJK KR', 'Noto Sans CJK TC', 'Noto Sans Lisu', 'Noto Sans Mono CJK HK',
    #                             'Noto Sans Mono CJK SC', 'Noto Sans Mono CJK TC', 'Noto Serif', 'Noto Serif CJK JP',
    #                             'Noto Serif CJK KR', 'Noto Serif CJK SC', 'Noto Serif CJK TC', 'Noto Serif Georgian',
    #                             'Noto Serif Italic', 'Noto Serif Lao', 'OpenSymbol', 'Oswald', 'PMingLiU',
    #                             'PMingLiU-ExtB', 'Palatino', 'Palatino Linotype', 'Roboto', 'Roboto Black',
    #                             'Roboto Light', 'Roboto Medium', 'Roboto Thin', 'Segoe Print', 'Segoe Script',
    #                             'Segoe UI', 'Segoe UI Light', 'Segoe UI Semibold', 'Segoe UI Semilight',
    #                             'Segoe UI Symbol', 'SimSun', 'SimSun-ExtB', 'Sylfaen', 'Symbol', 'Tahoma',
    #                             'Times New Roman', 'Times New Roman Baltic', 'Times New Roman CE',
    #                             'Times New Roman Cyr', 'Times New Roman Greek', 'Times New Roman TUR', 'Trebuchet MS',
    #                             'Verdana', 'Webdings', 'Wingdings', 'Wingdings 2', 'Wingdings 3', 'Yu Gothic',
    #                             'Yu Gothic UI', 'Zapf Dingbats']},
    #      'mediaDevices': {'enableMasking': True, 'uid': '626cf7336aee4d119d861e55b79d8012a205e0c8dd2e410ea25c329617',
    #                       'videoInputs': 0, 'audioInputs': 0, 'audioOutputs': 1},
    #      'webRTC': {'enable': True, 'isEmptyIceList': True, 'mode': 'alerted', 'enabled': True, 'customize': True,
    #                 'localIpMasking': True, 'fillBasedOnIp': True, 'publicIp': '', 'localIps': []},
    #      'webGL': {'mode': 'off', 'getClientRectsNoise': 1.18824, 'noise': 97.172},
    #      'clientRects': {'mode': 'off', 'noise': 1.18824},
    #      'webGLMetadata': {'mode': 'mask', 'vendor': 'Google Inc. (AMD)',
    #                        'renderer': 'ANGLE (AMD, AMD Radeon R7 Graphics (0x00009874) Direct3D11 vs_5_0 ps_5_0, D3D11)'},
    #      'webglParams': {'glCanvas': 'webgl2', 'supportedFunctions': [{'name': 'beginQuery', 'supported': True},
    #                                                                   {'name': 'beginTransformFeedback',
    #                                                                    'supported': True},
    #                                                                   {'name': 'bindBufferBase', 'supported': True},
    #                                                                   {'name': 'bindBufferRange', 'supported': True},
    #                                                                   {'name': 'bindSampler', 'supported': True},
    #                                                                   {'name': 'bindTransformFeedback',
    #                                                                    'supported': True},
    #                                                                   {'name': 'bindVertexArray', 'supported': True},
    #                                                                   {'name': 'blitFramebuffer', 'supported': True},
    #                                                                   {'name': 'clearBufferfi', 'supported': True},
    #                                                                   {'name': 'clearBufferfv', 'supported': True},
    #                                                                   {'name': 'clearBufferiv', 'supported': True},
    #                                                                   {'name': 'clearBufferuiv', 'supported': True},
    #                                                                   {'name': 'clientWaitSync', 'supported': True},
    #                                                                   {'name': 'compressedTexImage3D',
    #                                                                    'supported': True},
    #                                                                   {'name': 'compressedTexSubImage3D',
    #                                                                    'supported': True},
    #                                                                   {'name': 'copyBufferSubData', 'supported': True},
    #                                                                   {'name': 'copyTexSubImage3D', 'supported': True},
    #                                                                   {'name': 'createQuery', 'supported': True},
    #                                                                   {'name': 'createSampler', 'supported': True},
    #                                                                   {'name': 'createTransformFeedback',
    #                                                                    'supported': True},
    #                                                                   {'name': 'createVertexArray', 'supported': True},
    #                                                                   {'name': 'deleteQuery', 'supported': True},
    #                                                                   {'name': 'deleteSampler', 'supported': True},
    #                                                                   {'name': 'deleteSync', 'supported': True},
    #                                                                   {'name': 'deleteTransformFeedback',
    #                                                                    'supported': True},
    #                                                                   {'name': 'deleteVertexArray', 'supported': True},
    #                                                                   {'name': 'drawArraysInstanced',
    #                                                                    'supported': True},
    #                                                                   {'name': 'drawBuffers', 'supported': True},
    #                                                                   {'name': 'drawElementsInstanced',
    #                                                                    'supported': True},
    #                                                                   {'name': 'drawRangeElements', 'supported': True},
    #                                                                   {'name': 'endQuery', 'supported': True},
    #                                                                   {'name': 'endTransformFeedback',
    #                                                                    'supported': True},
    #                                                                   {'name': 'fenceSync', 'supported': True},
    #                                                                   {'name': 'framebufferTextureLayer',
    #                                                                    'supported': True},
    #                                                                   {'name': 'getActiveUniformBlockName',
    #                                                                    'supported': True},
    #                                                                   {'name': 'getActiveUniformBlockParameter',
    #                                                                    'supported': True},
    #                                                                   {'name': 'getActiveUniforms', 'supported': True},
    #                                                                   {'name': 'getBufferSubData', 'supported': True},
    #                                                                   {'name': 'getFragDataLocation',
    #                                                                    'supported': True},
    #                                                                   {'name': 'getIndexedParameter',
    #                                                                    'supported': True},
    #                                                                   {'name': 'getInternalformatParameter',
    #                                                                    'supported': True},
    #                                                                   {'name': 'getQuery', 'supported': True},
    #                                                                   {'name': 'getQueryParameter', 'supported': True},
    #                                                                   {'name': 'getSamplerParameter',
    #                                                                    'supported': True},
    #                                                                   {'name': 'getSyncParameter', 'supported': True},
    #                                                                   {'name': 'getTransformFeedbackVarying',
    #                                                                    'supported': True},
    #                                                                   {'name': 'getUniformBlockIndex',
    #                                                                    'supported': True},
    #                                                                   {'name': 'getUniformIndices', 'supported': True},
    #                                                                   {'name': 'invalidateFramebuffer',
    #                                                                    'supported': True},
    #                                                                   {'name': 'invalidateSubFramebuffer',
    #                                                                    'supported': True},
    #                                                                   {'name': 'isQuery', 'supported': True},
    #                                                                   {'name': 'isSampler', 'supported': True},
    #                                                                   {'name': 'isSync', 'supported': True},
    #                                                                   {'name': 'isTransformFeedback',
    #                                                                    'supported': True},
    #                                                                   {'name': 'isVertexArray', 'supported': True},
    #                                                                   {'name': 'pauseTransformFeedback',
    #                                                                    'supported': True},
    #                                                                   {'name': 'readBuffer', 'supported': True},
    #                                                                   {'name': 'renderbufferStorageMultisample',
    #                                                                    'supported': True},
    #                                                                   {'name': 'resumeTransformFeedback',
    #                                                                    'supported': True},
    #                                                                   {'name': 'samplerParameterf', 'supported': True},
    #                                                                   {'name': 'samplerParameteri', 'supported': True},
    #                                                                   {'name': 'texImage3D', 'supported': True},
    #                                                                   {'name': 'texStorage2D', 'supported': True},
    #                                                                   {'name': 'texStorage3D', 'supported': True},
    #                                                                   {'name': 'texSubImage3D', 'supported': True},
    #                                                                   {'name': 'transformFeedbackVaryings',
    #                                                                    'supported': True},
    #                                                                   {'name': 'uniform1ui', 'supported': True},
    #                                                                   {'name': 'uniform1uiv', 'supported': True},
    #                                                                   {'name': 'uniform2ui', 'supported': True},
    #                                                                   {'name': 'uniform2uiv', 'supported': True},
    #                                                                   {'name': 'uniform3ui', 'supported': True},
    #                                                                   {'name': 'uniform3uiv', 'supported': True},
    #                                                                   {'name': 'uniform4ui', 'supported': True},
    #                                                                   {'name': 'uniform4uiv', 'supported': True},
    #                                                                   {'name': 'uniformBlockBinding',
    #                                                                    'supported': True},
    #                                                                   {'name': 'uniformMatrix2x3fv', 'supported': True},
    #                                                                   {'name': 'uniformMatrix2x4fv', 'supported': True},
    #                                                                   {'name': 'uniformMatrix3x2fv', 'supported': True},
    #                                                                   {'name': 'uniformMatrix3x4fv', 'supported': True},
    #                                                                   {'name': 'uniformMatrix4x2fv', 'supported': True},
    #                                                                   {'name': 'uniformMatrix4x3fv', 'supported': True},
    #                                                                   {'name': 'vertexAttribDivisor',
    #                                                                    'supported': True},
    #                                                                   {'name': 'vertexAttribI4i', 'supported': True},
    #                                                                   {'name': 'vertexAttribI4iv', 'supported': True},
    #                                                                   {'name': 'vertexAttribI4ui', 'supported': True},
    #                                                                   {'name': 'vertexAttribI4uiv', 'supported': True},
    #                                                                   {'name': 'vertexAttribIPointer',
    #                                                                    'supported': True},
    #                                                                   {'name': 'waitSync', 'supported': True}],
    #                      'glParamValues': [{'name': 'ALIASED_LINE_WIDTH_RANGE', 'value': {'0': 1, '1': 1}},
    #                                        {'name': 'ALIASED_POINT_SIZE_RANGE', 'value': {'0': 1, '1': 1024}},
    #                                        {'name': ['DEPTH_BITS', 'STENCIL_BITS'], 'value': 'n/a'},
    #                                        {'name': 'MAX_3D_TEXTURE_SIZE', 'value': 2048},
    #                                        {'name': 'MAX_ARRAY_TEXTURE_LAYERS', 'value': 2048},
    #                                        {'name': 'MAX_COLOR_ATTACHMENTS', 'value': 8},
    #                                        {'name': 'MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS', 'value': 200704},
    #                                        {'name': 'MAX_COMBINED_TEXTURE_IMAGE_UNITS', 'value': 32},
    #                                        {'name': 'MAX_COMBINED_UNIFORM_BLOCKS', 'value': 24},
    #                                        {'name': 'MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS', 'value': 212992},
    #                                        {'name': 'MAX_CUBE_MAP_TEXTURE_SIZE', 'value': 16384},
    #                                        {'name': 'MAX_DRAW_BUFFERS', 'value': 8},
    #                                        {'name': 'MAX_FRAGMENT_INPUT_COMPONENTS', 'value': 120},
    #                                        {'name': 'MAX_FRAGMENT_UNIFORM_BLOCKS', 'value': 12},
    #                                        {'name': 'MAX_FRAGMENT_UNIFORM_COMPONENTS', 'value': 4096},
    #                                        {'name': 'MAX_FRAGMENT_UNIFORM_VECTORS', 'value': 1024},
    #                                        {'name': 'MAX_PROGRAM_TEXEL_OFFSET', 'value': 7},
    #                                        {'name': 'MAX_RENDERBUFFER_SIZE', 'value': 16384},
    #                                        {'name': 'MAX_SAMPLES', 'value': 8},
    #                                        {'name': 'MAX_TEXTURE_IMAGE_UNITS', 'value': 16},
    #                                        {'name': 'MAX_TEXTURE_LOD_BIAS', 'value': 2},
    #                                        {'name': 'MAX_TEXTURE_SIZE', 'value': 16384},
    #                                        {'name': 'MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS', 'value': 120},
    #                                        {'name': 'MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS', 'value': 4},
    #                                        {'name': 'MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS', 'value': 4},
    #                                        {'name': 'MAX_UNIFORM_BLOCK_SIZE', 'value': 65536},
    #                                        {'name': 'MAX_UNIFORM_BUFFER_BINDINGS', 'value': 24},
    #                                        {'name': 'MAX_VARYING_COMPONENTS', 'value': 120},
    #                                        {'name': 'MAX_VARYING_VECTORS', 'value': 30},
    #                                        {'name': 'MAX_VERTEX_ATTRIBS', 'value': 16},
    #                                        {'name': 'MAX_VERTEX_OUTPUT_COMPONENTS', 'value': 120},
    #                                        {'name': 'MAX_VERTEX_TEXTURE_IMAGE_UNITS', 'value': 16},
    #                                        {'name': 'MAX_VERTEX_UNIFORM_BLOCKS', 'value': 12},
    #                                        {'name': 'MAX_VERTEX_UNIFORM_COMPONENTS', 'value': 16384},
    #                                        {'name': 'MAX_VERTEX_UNIFORM_VECTORS', 'value': 4096},
    #                                        {'name': 'MAX_VIEWPORT_DIMS', 'value': {'0': 32767, '1': 32767}},
    #                                        {'name': 'MIN_PROGRAM_TEXEL_OFFSET', 'value': -8},
    #                                        {'name': ['RED_BITS', 'GREEN_BITS', 'BLUE_BITS', 'ALPHA_BITS'],
    #                                         'value': 'n/a'}, {'name': 'RENDERER', 'value': 'WebKit WebGL'},
    #                                        {'name': 'SHADING_LANGUAGE_VERSION',
    #                                         'value': 'WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)'},
    #                                        {'name': 'UNIFORM_BUFFER_OFFSET_ALIGNMENT', 'value': 256},
    #                                        {'name': 'VENDOR', 'value': 'WebKit'},
    #                                        {'name': 'VERSION', 'value': 'WebGL 2.0 (OpenGL ES 3.0 Chromium)'}],
    #                      'antialiasing': True, 'textureMaxAnisotropyExt': 16, 'shaiderPrecisionFormat': 'highp/highp',
    #                      'extensions': ['EXT_color_buffer_float', 'EXT_color_buffer_half_float',
    #                                     'EXT_disjoint_timer_query_webgl2', 'EXT_float_blend',
    #                                     'EXT_texture_compression_bptc', 'EXT_texture_compression_rgtc',
    #                                     'EXT_texture_filter_anisotropic', 'EXT_texture_norm16',
    #                                     'KHR_parallel_shader_compile', 'OES_draw_buffers_indexed',
    #                                     'OES_texture_float_linear', 'OVR_multiview2', 'WEBGL_clip_cull_distance',
    #                                     'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb',
    #                                     'WEBGL_debug_renderer_info', 'WEBGL_debug_shaders', 'WEBGL_lose_context',
    #                                     'WEBGL_multi_draw', 'WEBGL_provoking_vertex']},
    #      'extensions': {'enabled': True, 'preloadCustom': True, 'names': []}, 's3Path': 'zero_profile.zip',
    #      's3Date': '', 'devicePixelRatio': 1.25, 'checkCookies': False,
    #      'chromeExtensions': [], 'userChromeExtensions': [],
    #      'permissions': {'transferProfile': True, 'transferToMyWorkspace': True, 'shareProfile': True,
    #                      'manageFolders': True, 'editProfile': True, 'deleteProfile': True, 'cloneProfile': True,
    #                      'exportProfile': True, 'updateUA': True, 'addVpnUfoProxy': True, 'runProfile': True,
    #                      'viewProfile': True, 'addProfileTag': True, 'removeProfileTag': True, 'viewShareLinks': True,
    #                      'createShareLinks': True, 'updateShareLinks': True, 'deleteShareLinks': True}}
    # )
    profile_id = gl.create(
        {'name': GologinName, 'notes': '',
         'facebookAccountData': {'notParsedData': {}}, 'browserType': 'chrome', 'canBeRunning': True, 'os': 'win',
         'startUrl': '', 'autoLang': True, 'bookmarks': {}, 'googleServicesEnabled': False, 'isBookmarksSynced': True,
         'lockEnabled': False, 'debugMode': False, 'navigator': {
            'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.110 Safari/537.36',
            'resolution': '2304x1440', 'language': 'en-US,en;q=0.9', 'platform': 'Win32', 'hardwareConcurrency': 4,
            'doNotTrack': None, 'deviceMemory': 8, 'maxTouchPoints': 0},
         'storage': {'local': True, 'extensions': True, 'bookmarks': True, 'history': True, 'passwords': True,
                     'session': True, 'indexedDb': False, 'enableExternalExtensions': False}, 'proxyEnabled': True,
         'autoProxyServer': '', 'autoProxyUsername': '', 'autoProxyPassword': '',
         'proxy': { 'mode': 'http', 'host': proxy[0], 'port': proxy[1],
                   'autoProxyRegion': 'us', 'torProxyRegion': 'us', 'username': '', 'password': ''}, 'dns': '',
         'plugins': {'enableVulnerable': True, 'enableFlash': True},
         'timezone': {'enabled': True, 'fillBasedOnIp': True, 'timezone': ''},
         'geolocation': {'mode': 'prompt', 'enabled': True, 'customize': True, 'fillBasedOnIp': True,
                         'isCustomCoordinates': False, 'latitude': 0, 'longitude': 0, 'accuracy': 10},
         'audioContext': {'mode': 'noise', 'noise': 2.174740528118e-08}, 'canvas': {'mode': 'off', 'noise': 0.76474414},
         'fonts': {'enableMasking': True, 'enableDomRect': True,
                   'families': ['AIGDT', 'AMGDT', 'Arial', 'Arial Baltic', 'Arial Black', 'Arial CE', 'Arial Cyr',
                                'Arial Greek', 'Arial Hebrew', 'Arial MT', 'Arial Narrow', 'Arial Rounded MT Bold',
                                'Arial TUR', 'Arial Unicode MS', 'Calibri', 'Calibri Light', 'Cambria', 'Cambria Math',
                                'Candara', 'Comic Sans MS', 'Consolas', 'Constantia', 'Corbel', 'Courier',
                                'Courier New', 'Courier New Baltic', 'Courier New CE', 'Courier New Cyr',
                                'Courier New Greek', 'Courier New TUR', 'David', 'David Libre', 'DejaVu Sans',
                                'DejaVu Sans Condensed', 'DejaVu Sans Mono', 'DejaVu Serif', 'DejaVu Serif Condensed',
                                'Ebrima', 'Frank Ruehl', 'Frank Ruehl Libre Black', 'Frank Ruehl Libre Light',
                                'Franklin Gothic Book', 'Franklin Gothic Demi', 'Franklin Gothic Demi Cond',
                                'Franklin Gothic Heavy', 'Franklin Gothic Medium', 'Franklin Gothic Medium Cond',
                                'Gabriola', 'Gadugi', 'Georgia', 'Gill Sans', 'Gill Sans MT', 'Gill Sans MT Condensed',
                                'Gill Sans MT Ext Condensed Bold', 'Gill Sans Ultra Bold',
                                'Gill Sans Ultra Bold Condensed', 'Impact', 'KacstBook', 'KacstLetter', 'KacstNaskh',
                                'KacstOffice', 'KacstTitlel', 'Leelawadee', 'Liberation Mono', 'Liberation Sans',
                                'Liberation Sans Narrow', 'Liberation Serif', 'Lucida Bright', 'Lucida Calligraphy',
                                'Lucida Console', 'Lucida Sans Unicode', 'MS Gothic', 'MS LineDraw', 'MS Mincho',
                                'MS Outlook', 'MS PGothic', 'MS PMincho', 'MS Reference Sans Serif',
                                'MS Reference Specialty', 'MS Sans Serif', 'MS Serif', 'MS UI Gothic', 'MV Boli',
                                'Malgun Gothic', 'Marlett', 'Microsoft Himalaya', 'Microsoft JhengHei',
                                'Microsoft JhengHei UI', 'Microsoft PhagsPa', 'Microsoft Sans Serif',
                                'Microsoft Tai Le', 'Microsoft Uighur', 'Microsoft YaHei', 'Microsoft Yi Baiti',
                                'MingLiU', 'MingLiU-ExtB', 'MingLiU_HKSCS', 'MingLiU_HKSCS-ExtB', 'Miriam',
                                'Miriam Fixed', 'Miriam Libre', 'Mongolian Baiti', 'NSimSun', 'Nirmala UI', 'Noto Mono',
                                'Noto Sans', 'Noto Sans Arabic UI', 'Noto Sans CJK HK', 'Noto Sans CJK JP',
                                'Noto Sans CJK KR', 'Noto Sans CJK TC', 'Noto Sans Lisu', 'Noto Sans Mono CJK HK',
                                'Noto Sans Mono CJK SC', 'Noto Sans Mono CJK TC', 'Noto Serif', 'Noto Serif CJK JP',
                                'Noto Serif CJK KR', 'Noto Serif CJK SC', 'Noto Serif CJK TC', 'Noto Serif Georgian',
                                'Noto Serif Italic', 'Noto Serif Lao', 'OpenSymbol', 'Oswald', 'PMingLiU',
                                'PMingLiU-ExtB', 'Palatino', 'Palatino Linotype', 'Roboto', 'Roboto Black',
                                'Roboto Light', 'Roboto Medium', 'Roboto Thin', 'Segoe Print', 'Segoe Script',
                                'Segoe UI', 'Segoe UI Light', 'Segoe UI Semibold', 'Segoe UI Semilight',
                                'Segoe UI Symbol', 'SimSun', 'SimSun-ExtB', 'Sylfaen', 'Symbol', 'Tahoma',
                                'Times New Roman', 'Times New Roman Baltic', 'Times New Roman CE',
                                'Times New Roman Cyr', 'Times New Roman Greek', 'Times New Roman TUR', 'Trebuchet MS',
                                'Verdana', 'Webdings', 'Wingdings', 'Wingdings 2', 'Wingdings 3', 'Yu Gothic',
                                'Yu Gothic UI', 'Zapf Dingbats']},
         'mediaDevices': {'enableMasking': True, 'uid': '626cf7336aee4d119d861e55b79d8012a205e0c8dd2e410ea25c329617',
                          'videoInputs': 0, 'audioInputs': 0, 'audioOutputs': 1},
         'webRTC': {'enable': True, 'isEmptyIceList': True, 'mode': 'alerted', 'enabled': True, 'customize': True,
                    'localIpMasking': False, 'fillBasedOnIp': True, 'publicIp': '', 'localIps': []},
         'webGL': {'mode': 'off', 'getClientRectsNoise': 1.18824, 'noise': 97.172},
         'clientRects': {'mode': 'off', 'noise': 1.18824},
         'webGLMetadata': {'mode': 'mask', 'vendor': 'Google Inc. (AMD)',
                           'renderer': 'ANGLE (AMD, AMD Radeon R7 Graphics (0x00009874) Direct3D11 vs_5_0 ps_5_0, D3D11)'},
         'webglParams': {'glCanvas': 'webgl2', 'supportedFunctions': [{'name': 'beginQuery', 'supported': True},
                                                                      {'name': 'beginTransformFeedback',
                                                                       'supported': True},
                                                                      {'name': 'bindBufferBase', 'supported': True},
                                                                      {'name': 'bindBufferRange', 'supported': True},
                                                                      {'name': 'bindSampler', 'supported': True},
                                                                      {'name': 'bindTransformFeedback',
                                                                       'supported': True},
                                                                      {'name': 'bindVertexArray', 'supported': True},
                                                                      {'name': 'blitFramebuffer', 'supported': True},
                                                                      {'name': 'clearBufferfi', 'supported': True},
                                                                      {'name': 'clearBufferfv', 'supported': True},
                                                                      {'name': 'clearBufferiv', 'supported': True},
                                                                      {'name': 'clearBufferuiv', 'supported': True},
                                                                      {'name': 'clientWaitSync', 'supported': True},
                                                                      {'name': 'compressedTexImage3D',
                                                                       'supported': True},
                                                                      {'name': 'compressedTexSubImage3D',
                                                                       'supported': True},
                                                                      {'name': 'copyBufferSubData', 'supported': True},
                                                                      {'name': 'copyTexSubImage3D', 'supported': True},
                                                                      {'name': 'createQuery', 'supported': True},
                                                                      {'name': 'createSampler', 'supported': True},
                                                                      {'name': 'createTransformFeedback',
                                                                       'supported': True},
                                                                      {'name': 'createVertexArray', 'supported': True},
                                                                      {'name': 'deleteQuery', 'supported': True},
                                                                      {'name': 'deleteSampler', 'supported': True},
                                                                      {'name': 'deleteSync', 'supported': True},
                                                                      {'name': 'deleteTransformFeedback',
                                                                       'supported': True},
                                                                      {'name': 'deleteVertexArray', 'supported': True},
                                                                      {'name': 'drawArraysInstanced',
                                                                       'supported': True},
                                                                      {'name': 'drawBuffers', 'supported': True},
                                                                      {'name': 'drawElementsInstanced',
                                                                       'supported': True},
                                                                      {'name': 'drawRangeElements', 'supported': True},
                                                                      {'name': 'endQuery', 'supported': True},
                                                                      {'name': 'endTransformFeedback',
                                                                       'supported': True},
                                                                      {'name': 'fenceSync', 'supported': True},
                                                                      {'name': 'framebufferTextureLayer',
                                                                       'supported': True},
                                                                      {'name': 'getActiveUniformBlockName',
                                                                       'supported': True},
                                                                      {'name': 'getActiveUniformBlockParameter',
                                                                       'supported': True},
                                                                      {'name': 'getActiveUniforms', 'supported': True},
                                                                      {'name': 'getBufferSubData', 'supported': True},
                                                                      {'name': 'getFragDataLocation',
                                                                       'supported': True},
                                                                      {'name': 'getIndexedParameter',
                                                                       'supported': True},
                                                                      {'name': 'getInternalformatParameter',
                                                                       'supported': True},
                                                                      {'name': 'getQuery', 'supported': True},
                                                                      {'name': 'getQueryParameter', 'supported': True},
                                                                      {'name': 'getSamplerParameter',
                                                                       'supported': True},
                                                                      {'name': 'getSyncParameter', 'supported': True},
                                                                      {'name': 'getTransformFeedbackVarying',
                                                                       'supported': True},
                                                                      {'name': 'getUniformBlockIndex',
                                                                       'supported': True},
                                                                      {'name': 'getUniformIndices', 'supported': True},
                                                                      {'name': 'invalidateFramebuffer',
                                                                       'supported': True},
                                                                      {'name': 'invalidateSubFramebuffer',
                                                                       'supported': True},
                                                                      {'name': 'isQuery', 'supported': True},
                                                                      {'name': 'isSampler', 'supported': True},
                                                                      {'name': 'isSync', 'supported': True},
                                                                      {'name': 'isTransformFeedback',
                                                                       'supported': True},
                                                                      {'name': 'isVertexArray', 'supported': True},
                                                                      {'name': 'pauseTransformFeedback',
                                                                       'supported': True},
                                                                      {'name': 'readBuffer', 'supported': True},
                                                                      {'name': 'renderbufferStorageMultisample',
                                                                       'supported': True},
                                                                      {'name': 'resumeTransformFeedback',
                                                                       'supported': True},
                                                                      {'name': 'samplerParameterf', 'supported': True},
                                                                      {'name': 'samplerParameteri', 'supported': True},
                                                                      {'name': 'texImage3D', 'supported': True},
                                                                      {'name': 'texStorage2D', 'supported': True},
                                                                      {'name': 'texStorage3D', 'supported': True},
                                                                      {'name': 'texSubImage3D', 'supported': True},
                                                                      {'name': 'transformFeedbackVaryings',
                                                                       'supported': True},
                                                                      {'name': 'uniform1ui', 'supported': True},
                                                                      {'name': 'uniform1uiv', 'supported': True},
                                                                      {'name': 'uniform2ui', 'supported': True},
                                                                      {'name': 'uniform2uiv', 'supported': True},
                                                                      {'name': 'uniform3ui', 'supported': True},
                                                                      {'name': 'uniform3uiv', 'supported': True},
                                                                      {'name': 'uniform4ui', 'supported': True},
                                                                      {'name': 'uniform4uiv', 'supported': True},
                                                                      {'name': 'uniformBlockBinding',
                                                                       'supported': True},
                                                                      {'name': 'uniformMatrix2x3fv', 'supported': True},
                                                                      {'name': 'uniformMatrix2x4fv', 'supported': True},
                                                                      {'name': 'uniformMatrix3x2fv', 'supported': True},
                                                                      {'name': 'uniformMatrix3x4fv', 'supported': True},
                                                                      {'name': 'uniformMatrix4x2fv', 'supported': True},
                                                                      {'name': 'uniformMatrix4x3fv', 'supported': True},
                                                                      {'name': 'vertexAttribDivisor',
                                                                       'supported': True},
                                                                      {'name': 'vertexAttribI4i', 'supported': True},
                                                                      {'name': 'vertexAttribI4iv', 'supported': True},
                                                                      {'name': 'vertexAttribI4ui', 'supported': True},
                                                                      {'name': 'vertexAttribI4uiv', 'supported': True},
                                                                      {'name': 'vertexAttribIPointer',
                                                                       'supported': True},
                                                                      {'name': 'waitSync', 'supported': True}],
                         'glParamValues': [{'name': 'ALIASED_LINE_WIDTH_RANGE', 'value': {'0': 1, '1': 1}},
                                           {'name': 'ALIASED_POINT_SIZE_RANGE', 'value': {'0': 1, '1': 1024}},
                                           {'name': ['DEPTH_BITS', 'STENCIL_BITS'], 'value': 'n/a'},
                                           {'name': 'MAX_3D_TEXTURE_SIZE', 'value': 2048},
                                           {'name': 'MAX_ARRAY_TEXTURE_LAYERS', 'value': 2048},
                                           {'name': 'MAX_COLOR_ATTACHMENTS', 'value': 8},
                                           {'name': 'MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS', 'value': 200704},
                                           {'name': 'MAX_COMBINED_TEXTURE_IMAGE_UNITS', 'value': 32},
                                           {'name': 'MAX_COMBINED_UNIFORM_BLOCKS', 'value': 24},
                                           {'name': 'MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS', 'value': 212992},
                                           {'name': 'MAX_CUBE_MAP_TEXTURE_SIZE', 'value': 16384},
                                           {'name': 'MAX_DRAW_BUFFERS', 'value': 8},
                                           {'name': 'MAX_FRAGMENT_INPUT_COMPONENTS', 'value': 120},
                                           {'name': 'MAX_FRAGMENT_UNIFORM_BLOCKS', 'value': 12},
                                           {'name': 'MAX_FRAGMENT_UNIFORM_COMPONENTS', 'value': 4096},
                                           {'name': 'MAX_FRAGMENT_UNIFORM_VECTORS', 'value': 1024},
                                           {'name': 'MAX_PROGRAM_TEXEL_OFFSET', 'value': 7},
                                           {'name': 'MAX_RENDERBUFFER_SIZE', 'value': 16384},
                                           {'name': 'MAX_SAMPLES', 'value': 8},
                                           {'name': 'MAX_TEXTURE_IMAGE_UNITS', 'value': 16},
                                           {'name': 'MAX_TEXTURE_LOD_BIAS', 'value': 2},
                                           {'name': 'MAX_TEXTURE_SIZE', 'value': 16384},
                                           {'name': 'MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS', 'value': 120},
                                           {'name': 'MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS', 'value': 4},
                                           {'name': 'MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS', 'value': 4},
                                           {'name': 'MAX_UNIFORM_BLOCK_SIZE', 'value': 65536},
                                           {'name': 'MAX_UNIFORM_BUFFER_BINDINGS', 'value': 24},
                                           {'name': 'MAX_VARYING_COMPONENTS', 'value': 120},
                                           {'name': 'MAX_VARYING_VECTORS', 'value': 30},
                                           {'name': 'MAX_VERTEX_ATTRIBS', 'value': 16},
                                           {'name': 'MAX_VERTEX_OUTPUT_COMPONENTS', 'value': 120},
                                           {'name': 'MAX_VERTEX_TEXTURE_IMAGE_UNITS', 'value': 16},
                                           {'name': 'MAX_VERTEX_UNIFORM_BLOCKS', 'value': 12},
                                           {'name': 'MAX_VERTEX_UNIFORM_COMPONENTS', 'value': 16384},
                                           {'name': 'MAX_VERTEX_UNIFORM_VECTORS', 'value': 4096},
                                           {'name': 'MAX_VIEWPORT_DIMS', 'value': {'0': 32767, '1': 32767}},
                                           {'name': 'MIN_PROGRAM_TEXEL_OFFSET', 'value': -8},
                                           {'name': ['RED_BITS', 'GREEN_BITS', 'BLUE_BITS', 'ALPHA_BITS'],
                                            'value': 'n/a'}, {'name': 'RENDERER', 'value': 'WebKit WebGL'},
                                           {'name': 'SHADING_LANGUAGE_VERSION',
                                            'value': 'WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)'},
                                           {'name': 'UNIFORM_BUFFER_OFFSET_ALIGNMENT', 'value': 256},
                                           {'name': 'VENDOR', 'value': 'WebKit'},
                                           {'name': 'VERSION', 'value': 'WebGL 2.0 (OpenGL ES 3.0 Chromium)'}],
                         'antialiasing': True, 'textureMaxAnisotropyExt': 16, 'shaiderPrecisionFormat': 'highp/highp',
                         'extensions': ['EXT_color_buffer_float', 'EXT_color_buffer_half_float',
                                        'EXT_disjoint_timer_query_webgl2', 'EXT_float_blend',
                                        'EXT_texture_compression_bptc', 'EXT_texture_compression_rgtc',
                                        'EXT_texture_filter_anisotropic', 'EXT_texture_norm16',
                                        'KHR_parallel_shader_compile', 'OES_draw_buffers_indexed',
                                        'OES_texture_float_linear', 'OVR_multiview2', 'WEBGL_clip_cull_distance',
                                        'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb',
                                        'WEBGL_debug_renderer_info', 'WEBGL_debug_shaders', 'WEBGL_lose_context',
                                        'WEBGL_multi_draw', 'WEBGL_provoking_vertex']},
         'extensions': {'enabled': True, 'preloadCustom': True, 'names': []}, 's3Path': 'zero_profile.zip',
         's3Date': '', 'devicePixelRatio': 1.25, 'owner': '66091a64fb6f1de9c8ec4a03', 'checkCookies': False,
         'chromeExtensions': [], 'userChromeExtensions': [],
         'permissions': {'transferProfile': True, 'transferToMyWorkspace': True, 'shareProfile': True,
                         'manageFolders': True, 'editProfile': True, 'deleteProfile': True, 'cloneProfile': True,
                         'exportProfile': True, 'updateUA': True, 'addVpnUfoProxy': True, 'runProfile': True,
                         'viewProfile': True, 'addProfileTag': True, 'removeProfileTag': True, 'viewShareLinks': True,
                         'createShareLinks': True, 'updateShareLinks': True, 'deleteShareLinks': True}}

    )
    print('profile id: ', profile_id)

    profile = gl.getProfile(profile_id)

    # print('new profile name=', profile.get("name"))

    sheet.update_cell(numberOfRow, 8, profile_id)

    profile_info = gl.getProfile(profile_id)

    # print(profile_info)

    return profile_id, first_name, last_name
